name: Update the SHA256 list
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '16 2 * * *'
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build mirrors
      run: |
        which curl rm unzip
        curl https://bazaar.abuse.ch/export/txt/sha256/full/ --output full.zip
        ls -la full.zip
        yes | unzip full.zip
        rm full.zip
    - name: Commit & Push
      uses: actions-x/commit@v6
      with:
          email: updatebot@iam-py-test.github.io
          name: Update bot
          branch: main
          message: Update the SHA256 list 
